param(
    [string]$ItemTableDir = "F:\Modding\KCD2-PAKS\Tables\Libs\Tables\item",
    [string]$OutputPath = "E:\SteamLibrary\steamapps\common\KingdomComeDeliverance2\Mods\takeoreat\Data\Scripts\TakeOrEat\TakeOrEatItemData.lua"
)

$ErrorActionPreference = "Stop"

$sourceFiles = @(
    "item.xml",
    "item__alchemy.xml",
    "item__dlc.xml",
    "item__rewards.xml",
    "item__reward.xml",
    "item__unique.xml",
    "item__system.xml",
    "item__aux.xml"
)

function ConvertTo-LuaString([string]$Value) {
    if ($null -eq $Value) { return '""' }
    return '"' + ($Value -replace '\\', '\\' -replace '"', '\"') + '"'
}

$rowsById = @{}
foreach ($fileName in $sourceFiles) {
    $path = Join-Path $ItemTableDir $fileName
    if (-not (Test-Path -LiteralPath $path)) {
        continue
    }

    [xml]$xml = Get-Content -LiteralPath $path
    $itemClasses = $xml.database.ItemClasses
    if ($null -eq $itemClasses) {
        continue
    }

    foreach ($food in $itemClasses.Food) {
        if ($null -eq $food.Id) {
            continue
        }

        $type = -1
        if ([string]$food.Type -match '^\d+$') {
            $type = [int]$food.Type
        }

        $uiSound = [string]$food.UiSound
        $kind = "eat"
        if ($uiSound -eq "ui_consume_drink" -or $type -eq 3 -or $type -eq 1) {
            $kind = "drink"
        }

        $id = ([string]$food.Id).ToLowerInvariant()
        if (-not $rowsById.ContainsKey($id)) {
            $rowsById[$id] = [pscustomobject]@{
                Id = $id
                Name = [string]$food.Name
                Kind = $kind
                Type = $type
                UiSound = $uiSound
                Source = $fileName
            }
        }
    }
}

$rows = @($rowsById.Values | Sort-Object Id)
$drinkCount = @($rows | Where-Object Kind -eq "drink").Count
$eatCount = @($rows | Where-Object Kind -eq "eat").Count

$out = New-Object System.Collections.Generic.List[string]
$out.Add("-- Generated by Tools/generate_takeoreat_item_data.ps1 from vanilla item class tables.")
$out.Add("-- Food rows: $($rows.Count), drink rows: $drinkCount, eat rows: $eatCount.")
$out.Add("-- Rule: drink when Food.UiSound == ui_consume_drink, Food.Type == 3, or Food.Type == 1 potion.")
$out.Add("-- Do not edit by hand; rerun the generator after table updates.")
$out.Add("TakeOrEat = TakeOrEat or {}")
$out.Add("TakeOrEat.itemData = TakeOrEat.itemData or {}")
$out.Add("TakeOrEat.itemData.foodClassIds = {")
foreach ($row in $rows) {
    $out.Add(("    [{0}] = {{ kind = {1}, name = {2}, type = {3}, uiSound = {4}, source = {5} }}," -f `
        (ConvertTo-LuaString $row.Id),
        (ConvertTo-LuaString $row.Kind),
        (ConvertTo-LuaString $row.Name),
        $row.Type,
        (ConvertTo-LuaString $row.UiSound),
        (ConvertTo-LuaString $row.Source)))
}
$out.Add("}")
$out.Add("TakeOrEat.itemData.drinkClassIds = {}")
$out.Add("for classId, data in pairs(TakeOrEat.itemData.foodClassIds) do")
$out.Add('    if data.kind == "drink" then')
$out.Add("        TakeOrEat.itemData.drinkClassIds[classId] = data")
$out.Add("    end")
$out.Add("end")

Set-Content -LiteralPath $OutputPath -Value $out -Encoding ASCII
Write-Host "Generated $($rows.Count) food rows ($drinkCount drink, $eatCount eat) -> $OutputPath"
